name: Deployment_on_main

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    name: Deployment
    runs-on: [self-hosted, onpremise, consumer]
    steps:
      - name: Run deployment script on on-premise Debian
        run: /home/glaw/repositories/erp-gf-sync/syncConsumer.sh > /home/glaw/logs/sync_consumer.log 2> /home/glaw/logs/sync_consumer_error.log
    
